---
- name: Deploy application
  hosts: app
  vars_files:
    - vars/main.yml

  vars:
    ansistrano_deploy_to: '{{deploy_path}}'
    ansistrano_keep_releases: 5
    ansistrano_shared_paths:
      - log
      - tmp
      - public/uploads
      - vendor/bundle

    ansistrano_shared_files:
      - config/schedule.yml

    ansistrano_deploy_via: 'git'
    ansistrano_git_repo: '{{app_repo}}'
    ansistrano_git_branch: '{{app_env}}'

  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }