---
- name: add key for passenger
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xAC40B2F7 state=present

- name: apt via https
  apt: name=apt-transport-https state=present

- name: apt add passenger repository
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main' state=present update_cache=yes

- name: install passenger
  apt: name=passenger

- name: remove apache2
  apt: name=apache2 state=absent

- name: install nginx
  apt: name=nginx-extras

- name: remove the default app
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf force=true
  notify: nginx restart

- name: configure nginx site
  template: src=site.conf.j2 dest=/etc/nginx/sites-enabled/{{app_name}}.conf force=true
  notify: nginx restart

- name: enable nginx stats
  template: src=nginx-stats.conf.j2 dest=/etc/nginx/sites-enabled/nginx-stats.conf
  notify: nginx restart
