#- name: installs sidekiq
#  command: gem install sidekiq creates=/usr/local/bin/sidekiq

- name: install sidekiq
  gem: name=sidekiq state=present user_install=no

- name: add sidekiq init script
  template: src=sidekiq.conf.j2 dest=/etc/init/sidekiq.conf mode=644

- name: add sidekiq workers init script
  template: src=workers.conf.j2 dest=/etc/init/workers.conf mode=644
